drop table AF_SMS_OP_LOG if exists;
create table AF_SMS_OP_LOG 
(
   ID                   bigint  generated by default as identity         not null,
   SERIAL_NO			bigint,
   PHONE_NO  			bigint,
   ITEM_ID				bigint,
   CREATE_TIME          TIMESTAMP            not null,
   FINISH_TIME          TIMESTAMP,
   CONTENT	            VARCHAR2(2048)       not null,
   STATUS               VARCHAR2(4)          not null,
   RET_CODE             VARCHAR2(10),
   RECEIVE_MSG          VARCHAR2(2048),
   constraint PK_SMS_OP_LOG primary key (ID)
);

create index AF_IDX_OP_LOG_SERIAL_NO on AF_SMS_OP_LOG(SERIAL_NO);
comment on table AF_SMS_OP_LOG is
'短信操作记录';
comment on column AF_SMS_OP_LOG.ID is
'ID';
comment on column AF_SMS_OP_LOG.SERIAL_NO is
'序列号';

drop table AF_PHONE_ITEM if exists;
create table AF_PHONE_ITEM 
(
   ID                   bigint  generated by default as identity         not null,
   PHONE_NO  			bigint,
   constraint PK_PHONE_ITEM  primary key (ID)
);
comment on table AF_PHONE_ITEM is
'待处理手机队列';

comment on column AF_PHONE_ITEM.ID is
'ID';